### ISSUE TITLE
Enable Neon Dreams

### ISSUE THREAD

**Issue by timkpaine** [yeebc/jupyterlab-neon-theme#7]
I've implemented [Neon Dreams](https://github.com/robb0wen/synthwave-vscode) glow, is this something you'd want as part of this library or should I make a separate theme?

**Comment by timkpaine** [comment]
![Screen Shot 2020-06-17 at 19 44 20](https://user-images.githubusercontent.com/3105306/84961713-019ee500-b0d3-11ea-90e3-339170063115.png)

**Comment by timkpaine** [comment]
![Screen Shot 2020-06-17 at 20 03 27](https://user-images.githubusercontent.com/3105306/84962794-a9b5ad80-b0d5-11ea-8c93-72818c931a8c.png)
ok I might have overdone it haha 
Let me know if you want it here as a second theme, otherwise ill move it over to my own repo.

**Comment by yeebc** [comment]
Hi, thank you for your interest in my theme. Neon Dreams is an excellent  VSCode theme that is  one of the inspirations for this theme. However, its glow version is not friendly for long-term use which I don't expect (but if you open presentation mode in jlab you can see I enable the glow for function name). Also, I didn't make some UI panels in gradient colors like Neon Dreams since I want to keep the layout simple and flat (Here you can see that actually there are many differences not just the color scheme compare to the original style).

**Comment by timkpaine** [comment]
@yeebc no worries, I'll port into my own extension, thanks for getting back to me!

**Comment by timkpaine** [comment]
https://github.com/timkpaine/jupyterlab_miami_nights
